### ISSUE TITLE
[BUG] Login error

### ISSUE THREAD

**Issue by Pryx** [Pryx/git-md-diff#60]
```
backend_1   | InternalOAuthError: Failed to fetch user profile
backend_1   |     at /usr/src/app/node_modules/passport-gitlab2/lib/strategy.js:82:19
backend_1   |     at passBackControl (/usr/src/app/node_modules/oauth/lib/oauth2.js:132:9)
backend_1   |     at IncomingMessage.<anonymous> (/usr/src/app/node_modules/oauth/lib/oauth2.js:157:7)
backend_1   |     at IncomingMessage.emit (node:events:381:22)
backend_1   |     at endReadableNT (node:internal/streams/readable:1307:12)
backend_1   |     at processTicksAndRejections (node:internal/process/task_queues:81:21)
```

**Comment by Pryx** [comment]
We cannot get the user profile, because it actually doesn't exist. Gitlab doesn't create an user account until you accept the terms. It redirects us without showing us this and causes the error to appear. Will fix this by just redirecting to an error page.

![image](https://user-images.githubusercontent.com/5222912/117329946-74ed4900-ae95-11eb-9636-81c0008a7218.png)
